<a href="https://colab.research.google.com/github/mhoch123/MAT422/blob/main/HW_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Homework 1.4
Authors: Megan Hoch and Bronwyn Curnow

#1.4.1 Singular Value Decomposition

 Let $A$ be an $mxn$ matrix with the dimension of $col(A)=r$. Then there exisits an $mxn$ matrix $\sum$, where the diagonal entries in D are the first $r$ signular values of $A \sigma_{1}\geq \sigma_{2} \geq \ldots \geq \sigma_{r} \geq 0$, and there exists an $mxm$ orthogonal matrix U and $nxn$ orthogonal matrix V such that: $A=U\sum V^T$

 **The Singular Value Decomposition:**Any factorization of the above equation with $U$ and $V$ orthogonal is called a singular value decomposition(SVD) of $A$

In [ ]:
import numpy as np
import random
from sklearn.decomposition import PCA


X = np.random.randint(10, size = (5,5))
u, E, v = np.linalg.svd(X)
print('u:', u, '\n')
print('E:',E, '\n')
print('v:',v, '\n')

u: [[-0.46673502 -0.39235356  0.58261121 -0.52670613 -0.10659235]
 [-0.40922255 -0.1420421  -0.66532203 -0.36579495  0.48569701]
 [-0.57023138 -0.36289643 -0.10003881  0.70410109 -0.19332939]
 [-0.44880688  0.68360197 -0.15559426 -0.17739311 -0.52495985]
 [-0.296823    0.47631634  0.42859471  0.24808878  0.66315713]] 

E: [21.3429713  10.16329162  5.79338315  4.39941951  3.04415821] 

v: [[-0.48317486 -0.5164273  -0.4571205  -0.29333233 -0.45259462]
 [-0.50634923  0.33988046 -0.51121459  0.11490787  0.59459865]
 [-0.58389939  0.33110362  0.60164943 -0.4240677  -0.08727227]
 [ 0.33916463 -0.1382099  -0.10741003 -0.81646172  0.43326519]
 [ 0.23276891  0.69932291 -0.3951981  -0.23304328 -0.49626141]] 



As we can see, numpy gives us the S, $\sum$ and $V^T$ matrices that form the *Singular Value Decomposition* of our matrix X.

#1.4.2 Low-Rank Matrix Approximations

**Induced Norm:** The 2-norm of a matrix $A \in \mathbb{R}^{nxm}$ is $\parallel A\parallel_{2} = max_{x\neq0,\parallel x \parallel =1} x^{T}A^{T}Ax$

For a matrix with SVD where $k<r$, $A_k = \sum_{j=1}^{k} \sigma_{j}u_{j}v_{j}^T$ and the rank of $A_k$ is exactly $k$.

#1.4.3 Principle Component Analysis

**Covariance Matrix:** The covariance matrix is the $pxp$ matrix $S$ defined by $S=\frac{1}{N-1}B^T$ and since the form $BB^T$ is positive semidefinite, so is $S$

**Principle Component Analysis:** The goal of this analysis (PCA) is to find $k,(k\leq p)$ orthonormal vectors $v_1,\ldots,v_k$, that maximize the objective function $\frac{1}{N} \sum_{i=1}^{N}\sum_{j=1}^{k}\langle X_i \cdot v_j\rangle ^{2}$

**Total Variance:** Total Variance = $tr(S)$,
$tr(S)= \frac{1}{N-1}\sum_{1}^{p} \lambda_{j}$

In [ ]:
Y = np.random.randint(10,size = (5,5))
print('Y:',Y,'\n')

pca = PCA(n_components=5, svd_solver='full')
pca.fit(Y)
print('Singular Values:', pca.singular_values_)
print('Explained Variances',pca.explained_variance_ratio_)
cov = pca.get_covariance()
print('\nCovariance Matrix:', cov)


Y: [[8 6 0 5 0]
 [3 9 6 3 2]
 [7 7 6 7 1]
 [5 0 2 7 7]
 [6 8 0 4 0]] 

Singular Values: [9.19966429e+00 6.74567675e+00 4.21624677e+00 6.96624124e-01
 9.74824579e-17]
Explained Variances [5.70308781e-01 3.06631771e-01 1.19789332e-01 3.27011570e-03
 6.40352399e-35]

Covariance Matrix: [[ 3.7  -0.5  -2.8   1.55 -2.5 ]
 [-0.5  12.5   3.   -4.5  -8.75]
 [-2.8   3.    9.2   0.3   1.  ]
 [ 1.55 -4.5   0.3   3.2   2.5 ]
 [-2.5  -8.75  1.    2.5   8.5 ]]


Here, we see some of the *PCA* of our matrix Y.