<a href="https://colab.research.google.com/github/mhoch123/MAT422/blob/main/Linear_Algebra_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Elements of Linear Algebra

Authors: Megan Hoch and Bronwyn Curnow




# 1.2.1 Linear Spaces

**Linear Combination:** A vector that is the sum of a subset of 2 or more vectors that are multiplied by a constant.

**Subspace:** a subspace V is said to be a subset($U⊆V$) if it is closed under both addition ($u_1+u_2∈U$) and multiplication ($αu_1∈U$). 0 is always in the subspace.

**Span:** when $w_1,\ldots,w_m∈V$, the span (span($w_1,\ldots,w_m$)) is the set of all linear combinations of $w_j$'s.

**ColumnSpace:** The columnspace of a matrix A (written as $Col(A)$) is the subspace of $Rᴺ$ spanned by the columms of $A$. The dimension of the columnspace is called the column rank of $A$.

**Rowspace:** The rowspace of a matrix $A$ (written as $Row(A)$) is the subspace of $Rᴺ$ spanned by the rows of $A$. The dimension of the rowspace is called the row rank of $A$.

**Linear Independence and Dependence:** Vectors are linearly independdent if none of them can be written as a linear combination of the others. Vectors are linearly dependent if they can be written as a combination of each other.

**Basis:** The basis of a matrix $A$ (or series of vectors) are the linearly independent vectors that span $A$.

**Dimension:** The dimension is the number of vectors required to span a matrix.






In [ ]:
import numpy as np
import random
import sympy

x = np.array(([1,2,3],[4,5,6],[7,8,9]))
xrref = sympy.Matrix(x).rref()
print(xrref)
print('\n')

y = np.array(([5,4,8],[11,2,4],[9,3,8]))
yrref = sympy.Matrix(y).rref()
print(yrref)

(Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1))


(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


The first matrix's columns are *Linearly Dependent,* since there is a free variable in the third column. The third column could be made with two of the second column minus the first column.

The second matrix's columns are *linearly indepdent.* No row could be made with a combination of the others, and the null space has only the trivial solution.

In [ ]:
def span(matrix):
  rref = sympy.Matrix(matrix).rref()
  if len(rref[1]) == 3:
    print(matrix.transpose())
  else:
    a = []
    i = 0
    while i < 2:
      print(matrix[:,rref[1][i]])
      i += 1
span(x)
print('\n')
span(y)

[1 4 7]
[2 5 8]


[[ 5 11  9]
 [ 4  2  3]
 [ 8  4  8]]


This code shows us the *span* of matrix x and y (or any 3x3 matrix). Since the vectors in x are *linearly dependent,* the third vector does not appear in the span. The columns in y are all *linearly independent,* so it's span contains all three columns.

In [ ]:
def Dimension(matrix):
  dim = matrix.shape[1]
  print(f'The dimension of this matrix is: {dim}')

Dimension(x)
Dimension(y)

The dimension of this matrix is: 3
The dimension of this matrix is: 3


This final example shows the concept of *dimension.* Since both x and y have three columns, they require three vectors to span, and are thus of *dimension* three.

# 1.2.2 Orthogonality


**Orthonormal:** If the $u_i$’s each have a norm of 1 and are pairwise orthogonal where for all $i$ and all $j\neq i$, $(u_i, u_j)= 0$ and $ \parallel u_i \parallel = 1$.


**Best Approximation Theorem:** In a linear subspace $(U \subseteq V)$ with a vector $(v \notin U)$  we want to find $v^*$ in $U$ that is closest to $v$ in the norm.

**Orthogonal Projection:** A linear subspace $(U \subseteq V)$ has a orthonormal basis $q_1, \ldots, q_m$ where the orthogonal projection of $v \in V$ on $U$ is $P_u v = \sum_{j=1}^{m} (v,q_j)q_j$.

**Projection:** ${\displaystyle \operatorname {proj} _{\mathbf {u} }(\mathbf {v} )={\frac {\langle \mathbf {u} ,\mathbf {v} \rangle }{\langle \mathbf {u} ,\mathbf {u} \rangle }}{\mathbf {u} }}$




In [ ]:
print(yrref)

As we can see, when reduced, this basis of y is *orthonormal*. Each vector is orthogonal to both others, and each vector has a norm of 1.

In [ ]:
def proj(u,v):
  projection = np.dot(u,v)/(np.dot(u,u))*u
  return projection

print(proj(x[0,:], y[0,:]))

[2.64285714 5.28571429 7.92857143]


The first row of the matrix x *projected* onto the first row of the matrix y.

#1.2.3 Gram-Schmidt Process



**Gram-Schmidt Process:** This is used to obtain the orthonormal basis of $span(a_1,\ldots,a_m)$ that is constructed of orthonormal vectors $q_1, \ldots,q_{i-1}$ , where $a_1, \ldots, a_m$ is linearly independent in $R^n$.


In [ ]:
v = np.array(([-6,5,-3],[-3,4,-6],[-6,2,-3]))
def Gram_Schmidt(v):
  E = v[:,0]/np.linalg.norm(v[:,0])
  F = v[:,1]-proj(v[:,0],v[:,1])
  G = v[:,2]-proj(v[:,0],v[:,2])-proj(F,v[:,2])
  F = F/np.linalg.norm(F)
  G = G/np.linalg.norm(G)
  return np.array((E,F,G))
Gram_Schmidt(v)

array([[-0.66666667, -0.33333333, -0.66666667],
       [ 0.33333333,  0.66666667, -0.66666667],
       [ 0.66666667, -0.66666667, -0.33333333]])

This shows the *Gram-Schmidt* process for a three column matrix (it's easily generalizable to more than three columns, the math behind it is the same, just takes a few more steps of coding). Each vector created is now *orthonormal* to each other.

#1.2.4 Eigenvalues and Eigenvectors


**Eigenvalues and Eigenvectors:** Let $A \in \mathbb{R}^{d\times d}$ be a square matrix such that $\lambda \in \mathbb{R}$ is an eigenvalue of $A$ if there exists a non-zero vector $( x \neq 0)$ where $Ax = \lambda x$. In this case, the vector $x$ is the eigenvector.

**Diagonalization of Symmetric Matrices:** A matrix $A$ is said to be orthogonally diagonalizable  if there is an orthogonal matrix $P$, where $P^{-1} = P^T$, and a diagonal matrix $D$ such that $A=PDP^T = PDP^{-1}$.



In [ ]:
import numpy as np
a=np.array([[1,1],[4,-2]])
val,vect = np.linalg.eig(a)

print("eignevalues: ", val)
print("eigenvectors: ", vect)

eignevalues:  [ 2. -3.]
eigenvectors:  [[ 0.70710678 -0.24253563]
 [ 0.70710678  0.9701425 ]]


This code shows how to find the *eigenvalues and eigenvectors* of a matrix.

In [ ]:
r = np.array(([6,-6,-12],[-3,3,6],[3,-3,-6]))
R = sympy.Matrix(r)
P,D = R.diagonalize()
print(f'P: {P}')
print('\n')
print(f'D: {D}')
print('These are the two matrices that make up the diagonalized version of R\n')
print(f'Original: {R}')
print(f'Diagonalized: {P*D*P.inv()}')




P: Matrix([[1, 2, 2], [1, 0, -1], [0, 1, 1]])


D: Matrix([[0, 0, 0], [0, 0, 0], [0, 0, 3]])
These are the two matrices that make up the diagonalized version of R

Original: Matrix([[6, -6, -12], [-3, 3, 6], [3, -3, -6]])
Diagonalized: Matrix([[6, -6, -12], [-3, 3, 6], [3, -3, -6]])


*Diagonalizing* a matrix allows us to decompose it to two matrices and get our original matrix back. Here we see the two matrices, and the original matrix again by multiplying together $PDP^{-1}$